name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v5

    - uses: nuget/setup-nuget@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Update version
      run: |
        (Get-Content -Path src\ExceptionVisualizer\ExceptionVisualizer.csproj) |
          ForEach-Object {$_ -Replace '<AssemblyVersion>0.1.0</AssemblyVersion>', '<AssemblyVersion>0.1.${{ github.run_number }}</AssemblyVersion>'} |
            Set-Content -Path src\ExceptionVisualizer\ExceptionVisualizer.csproj

    - name: Restore
      run: nuget restore

    - name: Build
      run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

    - uses: actions/upload-artifact@v4
      with:
        name: ExceptionVisualizer.vsix
        path: src\ExceptionVisualizer\bin\Release\net8.0-windows\ExceptionVisualizer.vsix

    - name: Create Release
      if: ${{ github.event_name == 'push' }}
      uses: softprops/action-gh-release@v2
      with:
        files: ./src/ExceptionVisualizer/bin/Release/net8.0-windows/ExceptionVisualizer.vsix
        tag_name: 0.1.${{ github.run_number }}
        name: 0.1.${{ github.run_number }}
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}